test connection mode added verbose mode added igd description mode added

diff --git a/upnp2mrtg b/upnp2mrtg
--- a/upnp2mrtg
+++ b/upnp2mrtg
@@ -22,7 +22,7 @@
 # 
 #  http://www.ANetzB.de/upnp2mrtg/
 #
-#  $Id: upnp2mrtg,v 1.6 2006/10/14 19:30:20 tomcat Exp $
+#  $Id: upnp2mrtg,v 1.7 2006/11/29 21:00:46 tomcat Exp $
 
 # default configuration
 HOST="fritz.box"
@@ -39,27 +39,33 @@ case $NETCAT in
     *) nc="nc" ;;
 esac
 
-ver_txt="upnp2mrtg, version $Revision: 1.6 $
-Copyright (C) 2005 Michael Tomschitz
+ver_txt="upnp2mrtg, version $Revision: 1.7 $
+Copyright (C) 2005-2006 Michael Tomschitz
 upnp2mrtg comes with ABSOLUTELY NO WARRANTY. This is free software,
 and you are welcome to redistribute it under certain conditions."
 
-help_txt="Usage: upnp2mrtg [-a <host>] [-p <port>] [-d] [-h] [-v]
+help_txt="Usage: upnp2mrtg [-a <host>] [-p <port>] [-d] [-h] [-i] [-v] [-V]
 
   -a <host> hostname or ip adress of upnp device
   -p <port> port to connect
   -d        debug mode
   -h        show help and exit
+  -i <file> get all igd description
+  -t        test connection
   -v        show upnp2mrtg version and exit
+  -V        be verbose for testing
 "
 
-while getopts "a:dhp:v" option; do
+while getopts "a:dhi:p:tvV" option; do
   case $option in
     a) HOST="$OPTARG";;
     d) set -x ;;
     h) echo "$help_txt"; exit 0;;
+    i) MODE=igd; IGDXML="$OPTARG";;
     p) PORT="$OPTARG";;
+    t) MODE="test";;
     v) echo "$ver_txt"; exit 0;;
+    V) VERBOSE=true;;
     ?) exit 1;;
   esac
 done
@@ -75,11 +81,11 @@ SOAPACTION: \"urn:schemas-upnp-org:service:$5:1#$6\""
 soap_form () {
   echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>
 <s:Envelope
-	xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\"
-	s:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\">
+        xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\"
+        s:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\">
     <s:Body>
         <u:$1 xmlns:u=\"urn:schemas-upnp-org:service:$2:1\" />
-     </s:Body>
+    </s:Body>
 </s:Envelope>"
 }
 get_attribute () {
@@ -100,12 +106,57 @@ shell_netcat () {
   exec 5<>/dev/tcp/$1/$2; cat >&5; cat <&5;
 }
 
+get_response () {
+  _get_response_rs="`echo "$1" | $nc $HOST $PORT 2>/dev/null`"
+  _get_response_rv=$?
+  echo "$_get_response_rs"
+  if ${VERBOSE:-false}; then
+    echo
+    echo "---- REQUEST: ----">&2
+    echo "$1">&2
+    echo "---- RESPONSE: ----">&2
+    echo "$_get_response_rs">&2
+    echo "----">&2
+  fi
+  return $_get_response_rv
+}
+request_header_http () {
+echo "GET $3 HTTP/1.0
+
+"
+}
+
+case $MODE in
+  test)
+    echo "GET /any.xml HTTP/1.0
+" | $nc $HOST $PORT >/dev/null
+    if [ $? -eq 0 ]; then
+      echo "OK"; exit 0
+    else
+      echo "Connection Error"; exit 1
+    fi;;
+  igd)
+    for igd in any igdconnSCPD igddesc igddslSCPD igdicfgSCPD; do
+      request="`request_header_http $HOST $PORT /$igd.xml`
+" 
+      rs="`get_response "$request"`"
+      if [ "$IGDXML" = "-" ]; then
+        echo "---- $igd.xml ----
+$rs"
+      else
+        echo "---- $igd.xml ----
+$rs" >> "$IGDXML"
+      fi
+    done;;
+   *)
+
 # get uptime
 request="`soap_form GetStatusInfo WANIPConnection`"
 post="`request_header $HOST $PORT ${#request} WANIPConn1 WANIPConnection GetStatusInfo`
 
 $request"
-rs="`echo "$post" | $nc $HOST $PORT 2>/dev/null`"
+# rs="`echo "$post" | $nc $HOST $PORT 2>/dev/null`"
+rs="`get_response "$post"`"
 if [ $? -eq 0 ]; then
   ut=`get_attribute NewUptime "$rs"`
 
@@ -120,8 +171,8 @@ request="`soap_form GetAddonInfos WANCommonInterfaceConfig`"
 post="`request_header $HOST $PORT ${#request} WANCommonIFC1 WANCommonInterfaceConfig GetAddonInfos`
 
 $request"
-rs="`echo "$post" | $nc $HOST $PORT 2>/dev/null`"
-
+rs="`get_response "$post"`"
+# rs="`echo "$post" | $nc $HOST $PORT 2>/dev/null`"
 if [ $? -eq 0 ]; then
   b1=`get_attribute NewTotalBytesReceived "$rs"`
   b2=`get_attribute NewTotalBytesSent "$rs"`
@@ -130,3 +181,4 @@ fi
 # output for mrtg
 printf "%s\n%s\n%d days %.2d:%.2d:%.2d h (online)\nFritz!Box\n" \
   "${b1:-UNKNOWN}" "${b2:-UNKNOWN}" "${h% *}" "${h#* }" "${m#* }" "${s#* }"
+esac
